version: "3.8"
services:
  signum:
    image: signumnetwork/node:latest-h2
    deploy:
      replicas: 1
    restart: always
    ports:
      - "8121:8121"
      - "8123:8123"
      - "8125:8125"
    volumes:
      - "./conf:/conf"

