name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  publish-h2-image:
    environment: dockerhub-publish
    name: Push h2 db Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: damccull/signum
          tags: |
            type=semver,pattern={{version}}-h2
            type=raw,value=latest-h2
          flavor: |
            latest=false
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: 'Dockerfile.h2'
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  publish-maria-image:
    environment: dockerhub-publish
    name: Push mariadb Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: damccull/signum
          tags: |
            type=semver,pattern={{version}}-maria
            type=raw,value=latest-maria
          flavor: |
            latest=false
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: 'Dockerfile.mariadb'
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}